# Generated by Django 3.2.8 on 2022-02-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0003_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='limit',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
