# Generated by Django 3.2.8 on 2022-02-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0004_region_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamplesSniffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('name_uz', models.CharField(max_length=512, null=True, verbose_name='Viloyat nomi')),
                ('limit', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'samples_sniffer',
            },
        ),
    ]
