# Generated by Django 3.2.8 on 2022-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0005_samplessniffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name=('email address',)),
        ),
    ]
