# Generated by Django 3.2.8 on 2022-03-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coredata', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'MANAGER'), (2, 'COLLECTOR')], default=0),
        ),
    ]
