# Generated by Django 3.2.8 on 2022-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20220329_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='area_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='farm_name',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='inn_or_pinfl',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='layer_width',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
